SAC: images as observation: True
[[36m2022-02-07 00:06:43,466[0m][[34m__main__[0m][[32mINFO[0m] - SAC get_nets using: ['gripper_depth_obs', 'gripper_img_obs', 'robot_obs'][0m
[[36m2022-02-07 00:06:43,469[0m][[34m__main__[0m][[32mINFO[0m] - SAC get_nets: CNNPolicyRes, 	CNNCriticRes[0m
Error executing job with overrides: ['model_name=15objs', 'agent.learn_config.total_timesteps=500000', 'env_wrapper.max_target_dist=0.10', 'scene=tabletop_random_15objs', 'wandb_login.project=vapo_new']
Traceback (most recent call last):
  File "../scripts/train_tabletop.py", line 36, in main
    model = VAPOAgent(cfg,
  File "/mnt/ssd_shared/Users/Jessica/Documents/Thesis_ssd/vapo/vapo/agent/vapo_agent.py", line 49, in __init__
    self.target_search = TargetSearch(self.env,
  File "/mnt/ssd_shared/Users/Jessica/Documents/Thesis_ssd/vapo/vapo/agent/core/target_search.py", line 22, in __init__
    self.aff_net_static_cam = init_aff_net(aff_cfg)
  File "/mnt/ssd_shared/Users/Jessica/Documents/Thesis_ssd/vapo/vapo/utils/utils.py", line 46, in init_aff_net
    raise TypeError("Path does not exist: %s" % path)
TypeError: Path does not exist: /mnt/ssd_shared/Users/Jessica/Documents/Thesis_ssd/vapo/vapo/trained_models/tabletop_multiscene_static_sideview.ckpt

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
